AllCops:
  Exclude:
    - db/schema.rb

Rails/ActionFilter:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/Blocks:
  Enabled: false

RedundantReturn:
  AllowMultipleReturnValues: true

StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false
