language: ruby
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./script/bootstrap
notifications:
  slack:
    secure: JnVWYUGH28Rrqj/cb6QXNd0hCUvzeUmp1GtZeCCER2l65HMoXWKWjmRtrY2y91/HneBYsHN7GJfsOBdNVuyEUX/XgH2e/zkkQZgkYx/fyffzfbnE9M4BaAXiXeT7CqCDsGbRObXjki1C6tHz78VLdmm9HwbqnamKjWZWwGrgPWs=
rvm:
- 1.9.3
